# Generated by Django 6.0.4 on 2026-05-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewset_tipos_habs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('numero_disponibles', models.IntegerField()),
                ('tipo_habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewset_tipos_habs.tipohabitacion')),
            ],
        ),
    ]
