# Generated by Django 6.0.4 on 2026-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes_habs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenhabitacion',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
