# Generated by Django 6.0.4 on 2026-05-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewset_salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='viewset_salas.sala')),
            ],
        ),
    ]
