# Generated by Django 6.0.4 on 2026-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
